Traceback (most recent call last):
  File "dalton_bot.py", line 8, in <module>
    from daltonize import d_run, s_run
  File "/volume1/homes/Haych/Scripts/dalton-bot/daltonize.py", line 14, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
Traceback (most recent call last):
  File "dalton_bot.py", line 8, in <module>
    from daltonize import d_run, s_run
  File "/volume1/homes/Haych/Scripts/dalton-bot/daltonize.py", line 15, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
2021-03-31 17:24:37.549238: Logging in...
2021-03-31 17:24:37.693971: Logged in!
2021-03-31 17:24:42.168264: Found message from Haych13, contents: just need a random image to test

/u/dalton-bot
2021-03-31 17:24:42.935824: This is the post URL: https://i.redd.it/lqn4hn6sjcq61.jpg
2021-03-31 17:24:43.634824: Successfully downloaded image
2021-03-31 17:24:43.634960: Daltonizing...
2021-03-31 17:24:56.215558: Successfully daltonized images
2021-03-31 17:24:56.215734: Uploading daltonized images to Imgur...
2021-03-31 17:25:00.892098: This is the uploaded daltonized D-Image: https://i.imgur.com/i3jplf9.jpg, P-Image: https://i.imgur.com/hZzDCDz.jpg, T-Image: https://i.imgur.com/c1NOcdC.jpg
2021-03-31 17:25:01.321182: Comment made.

2021-03-31 17:25:03.824530: Found message from YourWorstCringev2, contents: u/Dalton-Bot
2021-03-31 17:25:05.118479: This is the post URL: https://i.redd.it/l834n55n64q61.jpg
2021-03-31 17:25:05.463425: Successfully downloaded image
2021-03-31 17:25:05.463568: Daltonizing...
2021-03-31 17:26:09.960627: Successfully daltonized images
2021-03-31 17:26:09.960855: Uploading daltonized images to Imgur...
2021-03-31 17:26:18.222656: This is the uploaded daltonized D-Image: https://i.imgur.com/xX3d5MX.jpg, P-Image: https://i.imgur.com/qiu37H3.jpg, T-Image: https://i.imgur.com/3mIhxnn.jpg
2021-03-31 17:26:19.145426: Comment made.

2021-03-31 18:44:06.106575: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16.0)
2021-03-31 18:46:20.670123: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f953632b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-03-31 18:48:34.330502: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f952ec970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-03-31 18:50:29.478651: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f952ec580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-03-31 19:16:25.192560: Logging in...
2021-03-31 19:16:25.416023: Logged in!
2021-03-31 21:25:07.791080: No data returned for comment t1_gsyd2fb
2021-03-31 21:25:18.498136: Found message from Street_Ad9810, contents: /u/dalton-bot
2021-03-31 21:25:18.724642: This is the post URL: https://i.redd.it/9y9h841lafq61.png
2021-03-31 21:25:19.326062: Successfully downloaded image
2021-03-31 21:25:19.326192: Daltonizing...
2021-03-31 21:25:26.564769: Successfully daltonized images
2021-03-31 21:25:26.564920: Uploading daltonized images to Imgur...
2021-03-31 21:25:31.646735: This is the uploaded daltonized D-Image: https://i.imgur.com/JZ1S1p0.jpg, P-Image: https://i.imgur.com/yK4dvql.jpg, T-Image: https://i.imgur.com/G7a7EBh.jpg
2021-03-31 21:25:32.050416: Comment made.

2021-03-31 22:35:07.713328: Found message from Patterson2020, contents: /u/dalton-bot
2021-03-31 22:35:08.106446: This is the post URL: https://i.redd.it/9y9h841lafq61.png
2021-03-31 22:35:09.249354: Successfully downloaded image
2021-03-31 22:35:09.249489: Daltonizing...
2021-03-31 22:35:16.262265: Successfully daltonized images
2021-03-31 22:35:16.262415: Uploading daltonized images to Imgur...
2021-03-31 22:35:20.242356: This is the uploaded daltonized D-Image: https://i.imgur.com/984RwBs.jpg, P-Image: https://i.imgur.com/Br3XBp8.jpg, T-Image: https://i.imgur.com/lwFc2b8.jpg
2021-03-31 22:35:20.602389: Comment made.

2021-04-01 03:48:02.231895: No data returned for comment t1_gszlla5
2021-04-01 03:48:13.096714: Found message from strat010, contents: u/dalton-bot
2021-04-01 03:48:13.724018: This is the post URL: https://www.reddit.com/gallery/l1dxbn
2021-04-01 03:48:15.903767: Failed to download. Post link was not an image.
2021-04-01 03:48:16.323635: Comment made.

2021-04-01 04:37:15.726305: No data returned for comment t1_gszqm9j
2021-04-01 04:37:27.095633: Found message from Street_Ad9810, contents: /u/dalton-bot
2021-04-01 04:37:27.352176: This is the post URL: https://i.redd.it/aaly2bsudhq61.png
2021-04-01 04:37:29.871695: Successfully downloaded image
2021-04-01 04:37:29.871848: Daltonizing...
2021-04-01 04:38:01.383601: Successfully daltonized images
2021-04-01 04:38:01.448170: Uploading daltonized images to Imgur...
2021-04-01 04:38:07.987361: This is the uploaded daltonized D-Image: https://i.imgur.com/XIkx1xy.jpg, P-Image: https://i.imgur.com/uXD9yhw.jpg, T-Image: https://i.imgur.com/64rPpNt.jpg
2021-04-01 04:38:08.438294: Comment made.

2021-04-01 10:16:26.817083: No data returned for comment t1_gt0fu8y
2021-04-01 10:16:37.760316: Found message from WhyIsJSONinMyPhone, contents: u/Dalton-bot
2021-04-01 10:16:38.070967: This is the post URL: https://imgur.com/ma0CmgC
2021-04-01 10:16:38.501569: Failed to download. Post link was not an image.
2021-04-01 10:16:38.909294: Comment made.

2021-04-01 12:15:57.585729: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8814ea00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 12:18:13.075050: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879eb2b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 12:20:25.606897: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879f0730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 12:22:39.890136: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879f0040>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 12:24:54.295063: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879e7be0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 12:27:00.491193: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879eb7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 12:29:45.746333: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797c880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 13:19:29.650949: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797ce80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 14:08:43.558397: Found message from callisto0108, contents: /u/dalton-bot WE NEED YOU!
2021-04-01 14:08:44.148116: This is the post URL: https://i.redd.it/fx36ysd83kq61.jpg
2021-04-01 14:09:08.987129: Successfully downloaded image
2021-04-01 14:09:08.987265: Daltonizing...
2021-04-01 14:09:19.340691: Successfully daltonized images
2021-04-01 14:09:19.340839: Uploading daltonized images to Imgur...
2021-04-01 14:11:00.131891: This is the uploaded daltonized D-Image: https://i.imgur.com/rz2KgCL.jpg, P-Image: https://i.imgur.com/YixDmmh.jpg, T-Image: https://i.imgur.com/MUASDXM.jpg
2021-04-01 14:11:07.172334: Comment made.

2021-04-01 14:18:57.740126: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879eb280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 14:20:57.841793: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-01 15:04:40.775061: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a2f970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-01 21:52:33.531901: No data returned for comment t1_gt2n7aq
2021-04-01 21:52:45.602840: Found message from Street_Ad9810, contents: ? Ok /u/dalton-bot
2021-04-01 21:52:45.947751: This is the post URL: https://i.redd.it/mkf7e45ckmq61.jpg
2021-04-01 21:52:47.245299: Successfully downloaded image
2021-04-01 21:52:47.245430: Daltonizing...
2021-04-01 21:52:56.108956: Successfully daltonized images
2021-04-01 21:52:56.109099: Uploading daltonized images to Imgur...
2021-04-01 21:53:03.511173: This is the uploaded daltonized D-Image: https://i.imgur.com/uwdT3uf.jpg, P-Image: https://i.imgur.com/w4JfiQc.jpg, T-Image: https://i.imgur.com/43nU946.jpg
2021-04-01 21:53:03.944525: Comment made.

2021-04-02 00:11:37.440379: No data returned for comment t1_gt33vca
2021-04-02 00:11:48.346600: Found message from Spy____, contents: u/dalton-bot
2021-04-02 00:11:49.064893: This is the post URL: https://i.redd.it/9y9h841lafq61.png
2021-04-02 00:11:51.939022: Successfully downloaded image
2021-04-02 00:11:51.939152: Daltonizing...
2021-04-02 00:11:58.828745: Successfully daltonized images
2021-04-02 00:11:58.828882: Uploading daltonized images to Imgur...
2021-04-02 00:12:08.562483: This is the uploaded daltonized D-Image: https://i.imgur.com/14SGxgC.jpg, P-Image: https://i.imgur.com/i4Y5oQs.jpg, T-Image: https://i.imgur.com/EcOY5YU.jpg
2021-04-02 00:12:09.025355: Comment made.

2021-04-02 00:12:09.806896: Found message from Spy____, contents: u/dalton-bot
2021-04-02 00:12:10.432744: This is the post URL: https://i.redd.it/9y9h841lafq61.png
2021-04-02 00:12:14.545237: Successfully downloaded image
2021-04-02 00:12:14.545368: Daltonizing...
2021-04-02 00:12:21.430276: Successfully daltonized images
2021-04-02 00:12:21.430421: Uploading daltonized images to Imgur...
2021-04-02 00:12:34.848659: This is the uploaded daltonized D-Image: https://i.imgur.com/1Mlq843.jpg, P-Image: https://i.imgur.com/WvSRNpX.jpg, T-Image: https://i.imgur.com/7EIrkGB.jpg
2021-04-02 00:12:36.001690: Comment made.

2021-04-02 00:42:26.601329: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879e7130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-02 03:34:09.207605: Found message from Street_Ad9810, contents: /u/dalton-bot
2021-04-02 03:34:14.800953: This is the post URL: https://i.redd.it/fwrfdabb9oq61.jpg
2021-04-02 03:34:54.080241: <urlopen error [Errno 104] Connection reset by peer>
2021-04-02 03:35:42.010047: Found message from Street_Ad9810, contents: /u/dalton-bot
2021-04-02 03:35:43.541434: This is the post URL: https://i.redd.it/fwrfdabb9oq61.jpg
2021-04-02 03:36:16.488031: Successfully downloaded image
2021-04-02 03:36:16.488167: Daltonizing...
2021-04-02 03:36:24.567785: Successfully daltonized images
2021-04-02 03:36:24.567957: Uploading daltonized images to Imgur...
2021-04-02 03:40:07.194762: This is the uploaded daltonized D-Image: https://i.imgur.com/YGxEuyJ.jpg, P-Image: https://i.imgur.com/wM1f7VO.jpg, T-Image: https://i.imgur.com/fsq0sPh.jpg
2021-04-02 03:40:20.341755: Comment made.

2021-04-02 04:40:27.046163: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-02 09:37:01.160236: Found message from hermandirkzw, contents: For my fellow colorblind Europeans: u/Dalton-bot
2021-04-02 09:37:05.906983: This is the post URL: https://i.redd.it/gfqxst8rqlq61.jpg
2021-04-02 09:37:06.894070: Successfully downloaded image
2021-04-02 09:37:06.894233: Daltonizing...
2021-04-02 09:37:57.367321: Successfully daltonized images
2021-04-02 09:37:57.367540: Uploading daltonized images to Imgur...
2021-04-02 09:38:19.242437: This is the uploaded daltonized D-Image: https://i.imgur.com/avaW3IJ.jpg, P-Image: https://i.imgur.com/jUAuJN5.jpg, T-Image: https://i.imgur.com/wIz2jRg.jpg
2021-04-02 09:38:20.603319: Comment made.

2021-04-02 16:07:12.465161: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-03 18:51:15.318245: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-03 19:06:42.269508: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-03 19:15:43.875231: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-03 19:19:30.645058: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879d3520>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-03 20:53:34.831927: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797c6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-03 20:56:44.285158: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 03:56:29.072037: Found message from AutoModerator, contents: This looks like an image post, calling /u/dalton-bot to daltonize the image.

*I am a bot, and this action was performed automatically. Please [contact the moderators of this subreddit](/message/compose/?to=/r/ColorBlind) if you have any questions or concerns.*
2021-04-04 03:56:29.493001: This is the post URL: https://i.redd.it/mj3jdey7n2r61.jpg
2021-04-04 03:56:33.269567: Successfully downloaded image
2021-04-04 03:56:33.269724: Daltonizing...
2021-04-04 04:10:50.744557: Successfully daltonized images
2021-04-04 04:10:50.828082: Uploading daltonized images to Imgur...
2021-04-04 04:13:12.397078: This is the uploaded daltonized D-Image: https://i.imgur.com/SgfmUB0.jpg, P-Image: https://i.imgur.com/qCN8Cbn.jpg, T-Image: https://i.imgur.com/PXNff2Y.jpg
2021-04-04 04:13:15.443904: Comment made.

2021-04-04 17:20:52.968558: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 18:05:22.064710: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879d3d00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-04 18:07:35.896012: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a20430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-04 18:09:33.280478: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 18:18:27.941042: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 19:10:27.710880: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 19:12:38.660881: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 19:26:30.611031: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 19:37:06.740980: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 19:45:54.790882: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 20:03:02.391071: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 21:04:16.880890: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 21:06:31.233723: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 21:23:04.997759: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 21:28:20.751080: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 22:42:18.074820: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 22:44:41.884021: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 23:18:58.481043: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 23:30:24.038429: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-04 23:32:40.841170: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 00:23:56.579039: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87944c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-05 00:57:28.931781: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 00:59:10.660861: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 01:16:48.177347: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 01:58:28.369669: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797c7f0>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-05 02:19:47.028853: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 02:56:00.658457: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879a0f70>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-05 03:14:05.438095: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 03:33:12.980254: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 03:34:56.306225: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 03:37:04.077292: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 03:38:28.627249: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 03:44:06.407538: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 03:47:11.757325: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797c640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-05 04:04:26.131438: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 04:07:16.202866: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 04:23:46.529472: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 04:28:53.004949: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 04:32:28.915623: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=16.0)
2021-04-05 04:34:36.613084: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87944280>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-05 04:39:51.883579: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 04:41:30.197371: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798b7c0>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-05 04:43:24.982799: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 05:00:59.757415: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 05:02:32.558045: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 05:11:34.477481: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 05:16:14.127419: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 05:34:31.287359: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798bac0>, 'Connection to www.reddit.com timed out. (connect timeout=16.0)'))
2021-04-05 05:36:05.187895: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=16.0)
2021-04-05 05:42:15.711791: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 06:08:41.927439: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 06:10:52.097520: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 06:32:05.835478: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 06:38:12.717786: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=16.0)
2021-04-05 06:55:58.957469: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 07:04:32.433101: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 07:20:53.567428: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 07:54:35.147509: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 08:09:25.627284: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 09:14:06.067456: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 09:22:48.717477: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 09:29:46.247789: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 09:45:41.943849: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 09:50:58.082521: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:20:04.157444: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:23:34.777315: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:25:49.267473: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:30:00.747550: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:32:14.747451: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:34:26.634772: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 10:59:16.957435: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 11:03:27.490383: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 11:15:31.298237: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 11:20:09.440084: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 11:51:49.509399: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 12:31:08.637295: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 12:35:23.947421: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 12:40:04.707458: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 12:44:11.887554: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 13:43:49.537486: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=16.0)
2021-04-05 13:45:59.680827: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Read timed out. (read timeout=16.0)
2021-04-05 13:52:09.177516: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:01:36.577660: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:06:34.798122: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:10:19.723669: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:12:36.876349: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:15:35.185636: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:20:26.879974: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 14:22:40.979782: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 15:05:58.917429: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 15:08:13.839978: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 15:16:16.617326: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 15:35:45.737443: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 16:13:56.638601: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 16:24:01.877440: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 17:20:27.721921: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 17:22:11.782812: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 17:34:45.182699: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879a0c10>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-05 17:36:33.102773: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 17:51:53.322614: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 17:59:39.797947: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 18:10:39.174056: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 18:12:53.286240: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 18:20:44.792779: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 18:22:56.402794: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 18:36:11.599437: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 18:38:26.512803: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 19:36:06.152798: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 19:47:15.882772: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 21:39:59.485002: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 21:42:08.248036: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 21:57:02.972843: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 22:22:10.392641: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 23:05:20.258225: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-05 23:34:38.502775: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:01:21.832775: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:04:58.812784: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:07:17.832791: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:09:29.310985: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:16:21.265541: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:18:54.342775: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:25:23.472893: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:32:03.037392: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 00:34:28.723055: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:14:11.112643: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:20:15.920601: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:22:30.702740: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:28:36.462752: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:30:49.462716: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:38:09.162486: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:51:16.592869: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 01:53:29.182760: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 02:15:40.892690: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879447c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 02:17:50.635197: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797c7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 02:20:58.068312: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879d3160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 02:23:07.672662: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879449d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 02:27:43.542787: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 02:30:56.903118: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 02:33:08.232786: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 02:35:21.986131: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 03:20:41.749329: received 502 HTTP response
2021-04-06 03:21:09.329316: received 502 HTTP response
2021-04-06 03:22:28.828717: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 03:24:02.332788: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 03:25:51.202786: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 03:27:23.254915: received 503 HTTP response
2021-04-06 03:29:29.585493: received 503 HTTP response
2021-04-06 03:31:34.217590: error with request EOF occurred in violation of protocol (_ssl.c:1124)
2021-04-06 04:11:51.427080: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 04:15:06.033683: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 07:29:46.608760: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 07:46:57.404288: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87944370>, 'Connection to oauth.reddit.com timed out. (connect timeout=16)'))
2021-04-06 07:49:02.143133: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 07:52:10.465136: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 08:08:42.942798: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 08:14:50.522776: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 08:26:07.322766: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 08:34:39.492782: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Read timed out. (read timeout=16)
2021-04-06 08:50:52.633251: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a06b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 08:52:49.889030: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798bc40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:04:51.691452: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795c2e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:07:05.838485: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87944c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:09:19.489020: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a200a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:11:32.352656: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798bb80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:13:45.707751: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87966100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:15:59.826863: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798b8e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:18:13.217997: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797cdc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:20:27.200732: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795cd60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:22:41.235679: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87966790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:24:56.289325: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795ca00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:27:10.719068: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798be20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:29:24.272689: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87966b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:31:38.397696: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87966640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:33:53.096211: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795c670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:36:06.994530: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8794b280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:38:21.987653: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a207f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:40:36.522691: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8794b460>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:42:51.112795: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795c7f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:45:05.527353: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795ca90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:47:19.502655: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879a0a00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:49:32.744422: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879666d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:51:47.297744: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795c730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:54:01.276517: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798b7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:56:15.972668: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797cdc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 09:58:30.513606: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8794ba90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:00:44.952677: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795cc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:02:59.886706: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87966580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:05:13.260010: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797c520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:07:28.562661: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795c3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:09:43.487737: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a20940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:11:58.782248: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a06b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:14:13.717895: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a20f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:16:27.982670: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8794bd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:18:41.961529: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8795c250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:20:55.544145: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8798b580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:23:10.954952: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8794bc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:25:24.708362: error with request HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8797cca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:45:31.417889: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87a20490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:45:45.216152: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8794b3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2021-04-06 10:45:58.989466: error with request HTTPSConnectionPool(host='oauth.reddit.com', port=443): Max retries exceeded with url: /message/unread/?mark=False&limit=1024&raw_json=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f879ca8e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
